import './js/loader';
import './js/header';
// import './js/library';
import './js/renderPage';
// import './js/gallery-lib';
import './js/team';
import '../node_modules/basiclightbox/dist/basicLightbox.min.css';
import './js/modalRender';
import './js/renderMainGallery';
import './js/renderPage';
import './js/get-trailer';
import './js/pagination';
import './js/headerButton';
